import UseOnCriterionAddedEventAddDefaultProductCriterionValuesListener from '@/Application/ProductCriterionValue/Listeners/UseOnCriterionAddedEventAddDefaultProductCriterionValues.listener';
import UseOnProductAddedEventAddDefaultProductCriterionValuesListener from '@/Application/ProductCriterionValue/Listeners/UseOnProductAddedEventAddDefaultProductCriterionValues.listener';
import UseOnCriterionRemovedEventRemoveAssociatedProductCriterionValuesListener from '@/Application/ProductCriterionValue/Listeners/UseOnCriterionRemovedEventRemoveAssociatedProductCriterionValues.listener';
import UseOnProductRemovedEventRemoveAssociatedProductCriterionValuesListener from '@/Application/ProductCriterionValue/Listeners/UseOnProductRemovedEventRemoveAssociatedProductCriterionValues.listener';

export default function UseGlobalHooks() {
  /**
   * Listeners
   */
  UseOnCriterionAddedEventAddDefaultProductCriterionValuesListener();
  UseOnProductAddedEventAddDefaultProductCriterionValuesListener();
  UseOnCriterionRemovedEventRemoveAssociatedProductCriterionValuesListener();
  UseOnProductRemovedEventRemoveAssociatedProductCriterionValuesListener();
}
